path: D:/gaura/Project/YOLO object detection/bone fracture detection/data
train: train/images
val: test/images

names:
  0: Comminuted
  1: Greenstick
  2: Healthy
  3: Linear
  4: Oblique Displaced
  5: Oblique
  6: Segmental
  7: Spiral
  8: Transverse Displaced
  9: Transverse
